spring.application.name=theses-api-indexation
spring.jackson.deserialization.fail-on-unknown-properties=true
referencement.index.name=referencement
referencement.index.mapping=classpath:indexs/referencement.json
es.hostname=${ES_HOSTNAME:localhost}
es.port=${ES_PORT:9200}
es.protocol=${ES_PROTOCOL:http}
es.username=${ES_USERNAME:}
es.password=${ES_PASSWORD:}
