spring.main.web-application-type=none
referencement.robots.url=${ROBOTS_URL:https://theses.fr/robots.txt}
referencement.robots.connect-timeout=${ROBOTS_CONNECT_TIMEOUT:5s}
referencement.robots.read-timeout=${ROBOTS_READ_TIMEOUT:30s}
